export const COLORS = [
  '#f9bc60',
  '#abd1c6',
  '#e16162',
  '#a786df',
  '#ffa8ba',
  '#6246ea',
  '#c759a7',
  '#009688',
  '#5ed9bd',
  '#4183d7',
  '#c2958c',
  '#6eb67b',
  '#ed7c59',
  '#9848be',
  '#4d3b86',
  '#c0d98a',
  '#b7321f',
  '#8db8d1',
  '#e5d727',
  '#264653',
] as const;

export const PERK_COST = {
  moveBack: 10,
  pourFromBottom: 50,
  addBottle: 100,
};

export const winMessages = [
  'Solved!',
  'You made it!',
  'Splendid sort!',
  'Liquid legend!',
  'Aqua ace!',
  'Puzzle master!',
  'Well done!',
  'Water whiz!',
  'Cascade champ!',
  'Great job!',
  'Bravo!',
  'Nailed it!',
  'Aqua win!',
  'Perfect pour!',
  'Fluid finesse!',
  'Pure precision!',
  'Stream star!',
  'Water ninja!',
  'H2-Woah!',
  'Genius!',
  'Well played!',
  'Outstanding!',
  'Amazing!',
  'Fantastic!',
  'Victory!',
  'Hydro hero!',
  'Flowing win!',
  'Perfect sort!',
];
